name: sixtyseconds event delegation
author: sixtyseconds
category: Native
tags: [element, delegation, addEvent, event, selector, events, denyEvent, delegateEvent, denyEvents, delegateEvents]
current: 0.5